apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: devsecblueprint
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: devsecblueprint
  template:
    metadata:
      labels:
        app: devsecblueprint
      annotations:
        restartedAt: "{{ now | date "2006-01-02T15:04:05Z07:00" }}"  # Adds a timestamp
    spec:
      containers:
      - name: devsecblueprint
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
